### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by snicholes** [220314-jwa/week1-code-kickstarrabbit#4]
day 1: missing summary of what is printed overall, also the snippet isn't a loop. some terminology (e.g. "result var defined" should be result var assigned) 75/100

day 2: ok but we are not testing - in the switch cases we are assigning values depending on which case we have. otherwise solid, mention of return good 80/100

day 3: missing summary of what is actually printed, if includes "!" which is not so if var does not contain cooked then add "cooked" to the name. 75/100

day 4: solid, line 8 is vague but otherwise good 90/100

day 5: good couldve had more detailed summary 95/100

**overall 83%**

**Comment by RedWinterDawn** [comment]
I'll take a B any day!
